robot-default:
  build: .
  volumes:
    - ./robots/default:/robots
    - ./output:/output
  tty: true
  environment:
    - ROBOT_TESTS=/robots/
    - BROWSER=firefox
  container_name: robot-testsuite